name: Manual Purge
on: workflow_dispatch
jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - run: python purge_old_data.py
      - run: git push
