name: Purge Old Detections
on:
  workflow_dispatch:   # manual trigger
  schedule:
    - cron: '0 2 * * *' # optional: daily at 02:00 UTC

jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Run purge script
        run: python purge_old_data.py

      - name: Push changes
        if: success()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git push origin HEAD:main --force-with-lease
